### ISSUE TITLE
Error changing device to Joystick

### ISSUE THREAD

**Issue by chunkypixel** [mutatedmonkey/game2d#10]
When you chose to change the device to Joystick an **Array index out of range** error is shown.

**Steps to reduce**
- Plug in your joystick (mine is an Xbox 360 controller)
- Compile and run your Asteroids demo
- On the Title screen, press **Esc**
- On the Game menu press **F12**
- On the Key Controls menu press **D**

The error appears to relate to returning the ButtonLabel (index is 1)

Note: I can play the game with the Joystick regardless of this selection so it is found/available.

**Comment by wiebow** [comment]
I tested with an Xbox 360 controller and PS3 pad, so interesting that it comes back, but I'll take a look tonight. Thanks for reporting.

The game does tell you it's a Xbox 360 stick though?

Yes, you can use the joystick in the game even if the device shown in the menu is Keyboard. What is shown in the menu has nothing to do with what is being polled in the example game. I do not check only the active device, although I could, but that is for the author of a game to decide.

**Comment by wiebow** [comment]
@chunkypixel  I'm starting the game, having my Xbox 360 controller plugged in, and it's working over here:

![selection_001](https://cloud.githubusercontent.com/assets/1338966/17058237/841a947a-501f-11e6-9ee3-93c7142b3414.png)

Can you make sure the module is re-compiled completely and try again?

**Comment by chunkypixel** [comment]
Ok, stepped through the code - looks to be picking up the generic DirectX identification for XInput instead an actual Xbox controller:
![joystick debug](https://cloud.githubusercontent.com/assets/20292815/17073837/d5ecf16a-50b7-11e6-851d-0fa550b72a46.png)

I then mapped that (XInput Controller #1) into your DetectJoystick method to the Xbox controller and it all worked OK:
![joystick debug2](https://cloud.githubusercontent.com/assets/20292815/17073878/4005598e-50b8-11e6-8a89-e50584fff5cf.png)

Note: Under this scenario I would assume there is still some issue around your UnknownStick class.  

Also according to this some/all might get mapped under XInput on Windows (i'm on Win 10 currently) : https://wiki.libsdl.org/SDL_GameControllerAddMapping

Hope that helps mate!

**Comment by wiebow** [comment]
So it seems that this different under Linux then!   Looks like I will need to take a look at this under Windows real soon.  I think I will ask Mark to look at this issue and let him tell if this is intended behaviour yes or no.

Thanks for the research!

edit: monkey2 issue here: https://github.com/blitz-research/monkey2/issues/35

**Comment by chunkypixel** [comment]
Pleasure!

**Comment by wiebow** [comment]
Logged into Windows and got the correct names for the sticks there:
- Xbox: XInput Controller #1
- PS3: PLAYSTATION(R)3 Controller
- PS4: Wireless Controller

Added these to the checklist. Closed the issue on monkey2 repo
Still looking why the unknown stick was not displayed. For now, I do not map any unknown stick, so the menu will report no stick attached.

**Comment by chunkypixel** [comment]
Looks good!
