### ISSUE TITLE
Method Enter not called on initial (base) State

### ISSUE THREAD

**Issue by chunkypixel** [mutatedmonkey/game2d#11]
The first initial provided 'State' (base/default ie. TITLESTATE in Asteroids) does not have it's Enter method called in the first initial start of your game.  Once you return to this state page it will be called as expected.

**Comment by wiebow** [comment]
Fixed this in the AddState method. Also made sure that the example game uses this by using the OnRestartGame() method. The enter method in the titlestate now clears out the EntityManager.
