### ISSUE TITLE
Make Entity.CheckCollision overridable

### ISSUE THREAD

**Issue by chunkypixel** [mutatedmonkey/game2d#13]
When creating your own custom 'entity' types if the CheckCollision method could be overridable so you could provide your own custom collision checks.

Note: The other aspect of the collision stuff is it's spread across both the entity and imageentiy objects.  That could be tidied up a little??

**Comment by wiebow** [comment]
Good suggestions, I will make the changes.

**Comment by wiebow** [comment]
Done.
