### ISSUE TITLE
Ability to set handle of image

### ISSUE THREAD

**Issue by chunkypixel** [mutatedmonkey/game2d#14]
The ability to set the image handle would be handy.  It could be done either (or both) during load or via an additional function:
**Examples**
`Method AddImage:Void(name:String, path:String, handle:Vec2f)
    Local image:= Image.Load(path)
        image.Handle=handle
    _images.Add( name, image )
End Method`

`Method SetImageHandle(name:String,handle:Vec2f)
    Local image:=GetImage(name)
    If (image<>Null) image.Handle=handle
End Method`

**Comment by wiebow** [comment]
Added this. Still need to push it though.
