### ISSUE TITLE
bug in joystick code

### ISSUE THREAD

**Issue by blitz-research** [mutatedmonkey/game2d#19]
Hi,

Found a little bug in the joystick code: if the _joystickDevice isn't recognized, _joystickDeviceMapping gets set to null.

But code such as JoystickHatValue doesn't check for this - it checks _joystickDevice, just not _joystickDeviceMapping - and you get a null object crash.

Bye!
Mark

**Comment by wiebow** [comment]
Fixed this by adding an extra check for these joystick methods. Thanks!
