### ISSUE TITLE
Gameplay 'freezes'

### ISSUE THREAD

**Issue by chunkypixel** [mutatedmonkey/game2d#21]
Wiebo,
Not sure if you have seen this (it happens only occasionally) when playing a game (I've seen this on both my Asteroids and your Choplifter) the game will all of a sudden 'freeze'.  If you hit ESC to display your menu and ESC to return to the game it continues to play fine.

Now not sure whether this is related to game2d or Monkey2? Also not sure how this could be debugged or even re-producible in a specific way without just playing and hoping?

**Comment by wiebow** [comment]
Hi. I have not seen this. I must admit that I have not played for extended times...  Have you had it  happen after long play sessions or also during short tests?

**Comment by chunkypixel** [comment]
It varies sometimes happens sometimes not.  Just wanted to see if you had noticed anything.  I'll keep and eye on it to see if I can find a cause but we can close it.
