### ISSUE TITLE
Add gamepad support to input manager

### ISSUE THREAD

**Issue by wiebow** [mutatedmonkey/game2d#9]
We should be able to use gamepads, and analog sticks and buttons.

**Comment by wiebow** [comment]
Started work on this. I will support PS3 and PS4 controllers first, and the wired Xbox 360 controller.

**Comment by chunkypixel** [comment]
This sounds great! Are you making your own module or getting prepared for Marks?

**Comment by wiebow** [comment]
Monkey2 already includes joystick recognition/reading etc. I'm creating the proper mapping from Monkey2 buttons and axes indexes to joystick/gamepad versions, and allowing game controls to be mapped to these.

**Comment by chunkypixel** [comment]
Ah sorry mate - hadn't realized that!

**Comment by wiebow** [comment]
No problem. SDL is pretty complete and that is what Monkey2 is using. The tough bit is incorporating the pad and config in a way that feels the same as I now have for keyboard controls.

**Comment by wiebow** [comment]
Incorporated the gamepad logic into the menus. Looks really nice. Xbox pad works perfect. PS pads behave badly; controls mapped to analog sticks can be changed only once and then they seem to be 'stuck'. Needs more work :)

**Comment by wiebow** [comment]
Done!

**Comment by wiebow** [comment]
I forgot to add hats :) So reopening and moving code around a bit to make this happen.

**Comment by wiebow** [comment]
Done again. Simplified design a bit, added Hat support, although simple.
